version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: teammate_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: teammate_db
      MYSQL_USER: teammate_user
      MYSQL_PASSWORD: teammate_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
